// Template file that the server will use to inject the React markup and
// initial state before sending it to the client
const template = opts => {
    return `
  <!DOCTYLE html>
  <html>
    <head>
      <title>Employee Directory</title>
      <meta name="description" content="Demonstrates how to dynamically generate images on the server">
      <!-- Bootstrap -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
      <!-- Custom CSS -->
      <link rel="stylesheet" href="/assets/custom.css" />
    </head>
    <body>
      <div id="root">${opts.body}</div>
    </body>
    <script>
      window.__initialState = ${opts.initialState}
    </script>
    <script src="/__/firebase/3.9.0/firebase-app.js"></script>
    <script src="/__/firebase/3.9.0/firebase-database.js"></script>
    <script src="/__/firebase/init.js"></script>
    <!-- Client bundle generated by webpack -->
    <script src='/assets/client.bundle.js'></script>
  </html>
  `;
};
module.exports = template;
//# sourceMappingURL=template.js.map